DROP TABLE IF EXISTS portfolios CASCADE;
 
CREATE TABLE portfolios (
 id SERIAL PRIMARY KEY NOT NULL,
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 name VARCHAR(255) NOT NULL,
 total_balance REAL NOT NULL DEFAULT 0
);

DROP TABLE portfolios;