DROP TABLE IF EXISTS portfolio_coins CASCADE;

CREATE TABLE portfolio_coins (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  coin_id INTEGER REFERENCES coins(id) ON DELETE CASCADE,
  holdings INTEGER NOT NULL
);